### ISSUE TITLE
Running PeopleSegmentationDemo on Android  App Crashes

### ISSUE THREAD

**Issue by charlizesmith** [nolanliou/PeopleSegmentationDemo#1]
Hello nolanliou,
I am trying to run your code on Android App. But app got crashes with the below error. Can you please help me to run the app.

>   Process: com.nolan.macesegmentationdemo, PID: 13738
>     **java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader**[DexPathList[[zip file "/data/app/com.nolan.macesegmentationdemo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.nolan.macesegmentationdemo-1/lib/arm, /system/lib, /vendor/lib]]] couldn't find "libmace_jni.so"
>         at java.lang.Runtime.loadLibrary0(Runtime.java:984)
>         at java.lang.System.loadLibrary(System.java:1567)
>         at com.xiaomi.mace.MaceJni.<clinit>(MaceJni.java:22)
>         at com.xiaomi.mace.MaceJni.getDeviceCapability(Native Method)
>         at com.nolan.macesegmentationdemo.segmentation.ModelSelector.select(ModelSelector.java:64)
>         at com.nolan.macesegmentationdemo.MainActivity$2.run(MainActivity.java:161)
>         at android.os.Handler.handleCallback(Handler.java:751)
>         at android.os.Handler.dispatchMessage(Handler.java:95)
>         at android.os.Looper.loop(Looper.java:154)
>         at android.os.HandlerThread.run(HandlerThread.java:61)

The second thing, I install the apk from your github page. It's working awesome with speed but the quality of output image is not that much good. Is it possible to increase the quality of output image? If yes then how to improve it? please help me out. thank you

**Comment by nolanliou** [comment]
There are some possible directions:
1. Use a more accurate dataset(maybe most import).
2. Add some fine-grained network(e.g. https://arxiv.org/abs/1912.08193)
2. Try some post-image processing.
